# ROAM
# R Open Abstraction Module Example Datasets
############################################

# ofp_Figure
ex01_Figure<-structure(list(word1 = c("no", "not", "not", "no", "not", "not", 
                         "not", "not", "no", "not", "no", "not", "not", "not", "no", "not", 
                         "no", "no", "not", "not", "not", "no", "not", "without", "never", 
                         "no", "not", "no", "no", "not", "not", "not", "no", "no", "no", 
                         "not", "not", "without", "never", "no", "not", "not", "not", 
                         "not", "not", "never", "no", "no", "not", "not", "not", "not", 
                         "not", "not", "not", "without", "no", "no", "no", "no", "no", 
                         "not", "not", "not", "not", "not", "not", "never", "no", "no", 
                         "no", "no", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "without", "never", "never", "never", "no", "no", 
                         "no", "no", "no", "no", "no", "no", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "without", "without", "never", "never", "no", "no", "no", "no", 
                         "no", "no", "no", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "without", 
                         "without", "without", "without", "without", "without", "never", 
                         "never", "never", "never", "never", "never", "never", "never", 
                         "never", "never", "never", "never", "no", "no", "no", "no", "no", 
                         "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", 
                         "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", 
                         "no", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "without", "without", 
                         "without", "without", "without", "without", "without", "without", 
                         "without", "without", "without", "without", "without", "never", 
                         "never", "never", "never", "never", "never", "never", "never", 
                         "never", "never", "never", "never", "never", "never", "never", 
                         "never", "never", "never", "never", "never", "never", "never", 
                         "never", "never", "never", "never", "never", "never", "never", 
                         "never", "never", "never", "never", "never", "never", "never", 
                         "never", "never", "never", "never", "never", "never", "never", 
                         "never", "no", "no", "no", "no", "no", "no", "no", "no", "no", 
                         "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", 
                         "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", 
                         "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", 
                         "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", 
                         "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", 
                         "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", 
                         "no", "no", "no", "no", "no", "no", "no", "no", "no", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "not", "not", "not", "not", "not", "not", "not", "not", 
                         "not", "without", "without", "without", "without", "without", 
                         "without", "without", "without", "without", "without", "without", 
                         "without", "without", "without", "without", "without", "without", 
                         "without", "without", "without", "without", "without", "without", 
                         "without", "without", "without", "without", "without", "without", 
                         "without", "without", "without", "without", "without", "without", 
                         "without", "without", "without", "without", "without", "without", 
                         "without", "without"), word2 = c("doubt", "like", "help", "no", 
                                                          "want", "wish", "allow", "care", "harm", "sorry", "great", "leave", 
                                                          "pretend", "worth", "pleasure", "love", "danger", "want", "afraid", 
                                                          "doubt", "fail", "good", "forget", "feeling", "forget", "matter", 
                                                          "avoid", "chance", "hope", "forgotten", "miss", "perfectly", 
                                                          "bad", "better", "opportunity", "admit", "fair", "delay", "failed", 
                                                          "wish", "dislike", "distress", "refuse", "regret", "trust", "want", 
                                                          "evil", "greater", "better", "blame", "deny", "escape", "fit", 
                                                          "hope", "suffer", "interruption", "affection", "apology", "cried", 
                                                          "help", "trouble", "deceive", "deceived", "despair", "envy", 
                                                          "ill", "prevent", "allow", "fear", "injury", "loss", "share", 
                                                          "agree", "certain", "disturb", "fond", "happy", "lost", "satisfied", 
                                                          "stop", "strike", "betraying", "agree", "failing", "loved", "advantage", 
                                                          "comfort", "confidence", "delay", "denying", "desire", "doubts", 
                                                          "positive", "comfortable", "daring", "detain", "fear", "forgive", 
                                                          "pay", "pleasant", "please", "strong", "suspect", "thank", "trouble", 
                                                          "wrong", "losing", "wishing", "liked", "wish", "fresh", "humour", 
                                                          "ill", "inconvenience", "interest", "natural", "pain", "accept", 
                                                          "adopt", "betray", "blind", "complain", "convinced", "cried", 
                                                          "disappoint", "disappointed", "excuse", "good", "join", "offend", 
                                                          "offended", "pain", "pity", "pleased", "promise", "reach", "share", 
                                                          "tired", "true", "unworthy", "wishing", "affection", "great", 
                                                          "hope", "hopes", "loss", "pain", "consent", "disgrace", "doubted", 
                                                          "forgive", "happy", "hope", "leave", "like", "safe", "suspected", 
                                                          "tired", "worth", "charm", "defect", "demand", "disguise", "dread", 
                                                          "encouragement", "escaping", "faith", "feeling", "hardship", 
                                                          "hindrance", "hopes", "importance", "kind", "leave", "limits", 
                                                          "love", "miss", "nonsense", "peace", "preventing", "promise", 
                                                          "remarkable", "smile", "thanks", "true", "waste", "worse", "accuse", 
                                                          "acquit", "adequate", "admire", "admiring", "alarm", "capable", 
                                                          "clever", "commit", "consent", "courage", "cut", "delay", "desirable", 
                                                          "detained", "discouraged", "disdain", "disgrace", "disgust", 
                                                          "easy", "encourage", "engage", "enjoy", "expose", "forced", "great", 
                                                          "hesitate", "impose", "inconvenient", "injured", "interest", 
                                                          "interrupt", "inviting", "kill", "mistake", "nerves", "perfect", 
                                                          "positively", "prepared", "promoted", "recommend", "relieve", 
                                                          "rich", "scold", "smile", "stopped", "struck", "suffering", "superior", 
                                                          "wonderful", "accident", "anger", "disguise", "disturbing", "falling", 
                                                          "fear", "gaining", "help", "love", "risk", "stopping", "success", 
                                                          "tears", "admit", "admitted", "alone", "appeased", "betrayed", 
                                                          "better", "bless", "bold", "brilliant", "complains", "dear", 
                                                          "desired", "discarded", "doubt", "dull", "easy", "encouraged", 
                                                          "esteemed", "excited", "fails", "fair", "fallen", "forgotten", 
                                                          "indifferent", "insult", "insulted", "killed", "love", "miss", 
                                                          "no", "offend", "pay", "pitied", "promised", "reach", "reached", 
                                                          "recommend", "rejoiced", "respected", "satisfied", "saved", "struck", 
                                                          "weary", "worn", "accusation", "active", "admitted", "advantages", 
                                                          "affectionate", "alarm", "amusement", "attraction", "authority", 
                                                          "benefit", "care", "cautious", "cheerful", "comfortable", "comforts", 
                                                          "contemptuous", "courage", "defects", "demands", "difficult", 
                                                          "disgrace", "dislike", "disputing", "distrust", "embarrassing", 
                                                          "embarrassment", "enemy", "envy", "excellence", "excuse", "fair", 
                                                          "feeble", "fine", "fire", "fond", "free", "grief", "happiness", 
                                                          "harsher", "important", "increase", "indifference", "indignant", 
                                                          "insignificant", "interruption", "laughing", "lurking", "mercy", 
                                                          "mistaking", "novel", "pity", "poverty", "pray", "pretty", "prospect", 
                                                          "regret", "regrets", "revenge", "risks", "scandalous", "selfish", 
                                                          "sigh", "smiles", "sorrow", "spirit", "stop", "strong", "success", 
                                                          "sullen", "superior", "support", "suspicious", "sweet", "tears", 
                                                          "thank", "triumph", "triumphant", "unacceptable", "unhappy", 
                                                          "unworthy", "useful", "violent", "warning", "yes", "abuse", "advanced", 
                                                          "affection", "affronted", "agreeable", "alarmed", "anger", "angry", 
                                                          "apologize", "ashamed", "astonished", "attack", "beloved", "betrayed", 
                                                          "calm", "cherish", "clash", "clear", "competent", "conciliating", 
                                                          "contend", "cruel", "danger", "dear", "deceiving", "defer", "demanding", 
                                                          "desire", "desperate", "destroy", "determined", "die", "disgusted", 
                                                          "disgusting", "displeased", "disregard", "distressed", "disturbed", 
                                                          "doomed", "dream", "encouragement", "entitled", "expel", "extend", 
                                                          "fallen", "fatigue", "foolish", "fortunate", "frightened", "granted", 
                                                          "growing", "hate", "helpless", "hopeless", "humour", "hurt", 
                                                          "improved", "increase", "inferior", "interrupted", "intimidate", 
                                                          "invite", "irritate", "kind", "laugh", "loving", "luckily", "mad", 
                                                          "misleading", "missed", "missing", "mistaken", "misunderstand", 
                                                          "neglect", "no", "nonsense", "pained", "pardon", "pleasure", 
                                                          "praise", "pretty", "prevented", "protect", "protest", "punish", 
                                                          "recommended", "remarkable", "resolve", "reward", "ruin", "safe", 
                                                          "safely", "shame", "smart", "strange", "stronger", "struggle", 
                                                          "suspected", "sympathy", "torture", "tragic", "ugly", "undesirable", 
                                                          "unfair", "warm", "waste", "welcomed", "win", "winning", "yes", 
                                                          "accepting", "admiring", "anguish", "apology", "attacking", "benefit", 
                                                          "chance", "contempt", "crying", "danger", "daring", "debt", "delight", 
                                                          "depressing", "elation", "embarrassment", "encouragement", "enjoying", 
                                                          "error", "exaggerated", "excuse", "fatigue", "fearing", "good", 
                                                          "ill", "improvement", "laughing", "loving", "mercy", "neglecting", 
                                                          "no", "obstacle", "offending", "poor", "praise", "regretting", 
                                                          "resolving", "selfishness", "strong", "suffering", "trembling", 
                                                          "violence", "warmth"), score = c(-1L, 2L, 2L, -1L, 1L, 1L, 1L, 
                                                                                           2L, -2L, -1L, 3L, -1L, -1L, 2L, 3L, 3L, -2L, 1L, -2L, -1L, -2L, 
                                                                                           3L, -1L, 1L, -1L, 1L, -1L, 2L, 2L, -1L, -2L, 3L, -3L, 2L, 2L, 
                                                                                           -1L, 2L, -1L, -2L, 1L, -2L, -2L, -2L, -2L, 1L, 1L, -3L, 3L, 2L, 
                                                                                           -2L, -2L, -1L, 1L, 2L, -2L, -2L, 3L, -1L, -2L, 2L, -2L, -3L, 
                                                                                           -3L, -3L, -1L, -2L, -1L, 1L, -2L, -2L, -3L, 1L, 1L, 1L, -2L, 
                                                                                           2L, 3L, -3L, 2L, -1L, -1L, -3L, 1L, -2L, 3L, 2L, 2L, 2L, -1L, 
                                                                                           -2L, 1L, -1L, 2L, 2L, 2L, -2L, -2L, 1L, -1L, 3L, 1L, 2L, -1L, 
                                                                                           2L, -2L, -2L, -3L, 1L, 2L, 1L, 1L, 2L, -2L, -2L, 1L, 1L, -2L, 
                                                                                           1L, 1L, -3L, -1L, -2L, 1L, -2L, -2L, -2L, -1L, 3L, 1L, -2L, -2L, 
                                                                                           -2L, -2L, 3L, 1L, 1L, 1L, -2L, 2L, -2L, 1L, 3L, 3L, 2L, 2L, -3L, 
                                                                                           -2L, 2L, -2L, -1L, 1L, 3L, 2L, -1L, 2L, 1L, -1L, -2L, 2L, 3L, 
                                                                                           -3L, -1L, -1L, -2L, 2L, -1L, 1L, 1L, -2L, -2L, 2L, 2L, 2L, -1L, 
                                                                                           -1L, 3L, -2L, -2L, 2L, -1L, 1L, 2L, 2L, 2L, 2L, -1L, -3L, -2L, 
                                                                                           2L, 1L, 3L, 3L, -2L, 1L, 2L, 1L, 2L, 2L, -1L, -1L, 2L, -2L, -2L, 
                                                                                           -2L, -2L, -3L, 1L, 2L, 1L, 2L, -1L, -1L, 3L, -2L, -1L, -2L, -2L, 
                                                                                           1L, -2L, 1L, -3L, -2L, -1L, 3L, 2L, 1L, 1L, 2L, 1L, 2L, -2L, 
                                                                                           2L, -1L, -1L, -2L, 2L, 4L, -2L, -3L, -1L, -2L, -1L, -2L, 2L, 
                                                                                           2L, 3L, -2L, -1L, 2L, -2L, -1L, -1L, -2L, 2L, -3L, 2L, 2L, 2L, 
                                                                                           4L, -2L, 2L, 2L, -1L, -1L, -2L, 1L, 2L, 2L, 3L, -2L, 2L, -2L, 
                                                                                           -1L, -2L, -2L, -2L, -3L, 3L, -2L, -1L, -2L, -1L, -1L, 1L, 1L, 
                                                                                           1L, 2L, 4L, 2L, 2L, 2L, -1L, -2L, -1L, -2L, 1L, -1L, 2L, 3L, 
                                                                                           -2L, 3L, 2L, 1L, 2L, 2L, -1L, 2L, 2L, 2L, -2L, 2L, -3L, -1L, 
                                                                                           -1L, -2L, -2L, -2L, -3L, -2L, -2L, -2L, -1L, 3L, -1L, 2L, -2L, 
                                                                                           2L, -2L, 2L, 1L, -2L, 3L, -2L, 2L, 1L, -2L, -2L, -2L, -2L, 1L, 
                                                                                           -1L, 2L, -2L, 2L, -2L, -1L, 1L, 1L, 1L, -2L, -2L, -2L, -2L, -3L, 
                                                                                           -3L, -2L, 2L, -2L, 1L, -1L, 2L, 2L, -2L, 2L, 2L, -2L, 2L, -2L, 
                                                                                           2L, 4L, 4L, -2L, -2L, -2L, 2L, -3L, -3L, 1L, -3L, 1L, 3L, -1L, 
                                                                                           2L, -2L, -3L, -3L, -1L, -2L, 2L, -1L, 3L, -3L, 2L, 2L, -2L, 1L, 
                                                                                           2L, 2L, -1L, -3L, -2L, 2L, -3L, -1L, -1L, 1L, -3L, -3L, 2L, -3L, 
                                                                                           -3L, -3L, -2L, -2L, -2L, -2L, -2L, 1L, 2L, 1L, -2L, 1L, -2L, 
                                                                                           -2L, -2L, 2L, -2L, 1L, 1L, -3L, -2L, -2L, 2L, -2L, 2L, 1L, -2L, 
                                                                                           -2L, -2L, 1L, -3L, 2L, 1L, 2L, 3L, -3L, -3L, -2L, -2L, -2L, -2L, 
                                                                                           -2L, -1L, -2L, -2L, 2L, 3L, 3L, 1L, -1L, 1L, -2L, -2L, 2L, 2L, 
                                                                                           2L, 2L, -2L, 1L, 1L, -2L, 1L, -1L, 2L, -2L, -1L, 2L, -4L, -2L, 
                                                                                           -3L, -2L, -2L, 1L, -1L, 2L, 4L, 4L, 1L, 1L, 3L, -3L, -1L, -1L, 
                                                                                           2L, 2L, -2L, -2L, -2L, 2L, -2L, 3L, -2L, 3L, -2L, 2L, 2L, -2L, 
                                                                                           -2L, -1L, -2L, -2L, 3L, -2L, 2L, 1L, 2L, 2L, -2L, -1L, -2L, -2L, 
                                                                                           -2L, 3L, -2L, 2L, -3L, 2L, -2L, -2L, -3L, 2L), n = c(102L, 99L, 
                                                                                                                                                82L, 60L, 45L, 39L, 36L, 23L, 22L, 21L, 19L, 18L, 18L, 17L, 16L, 
                                                                                                                                                16L, 15L, 15L, 15L, 14L, 14L, 13L, 13L, 13L, 12L, 12L, 12L, 11L, 
                                                                                                                                                11L, 10L, 10L, 10L, 9L, 9L, 9L, 9L, 9L, 9L, 8L, 8L, 8L, 8L, 8L, 
                                                                                                                                                8L, 8L, 7L, 7L, 7L, 7L, 7L, 7L, 7L, 7L, 7L, 7L, 7L, 6L, 6L, 6L, 
                                                                                                                                                6L, 6L, 6L, 6L, 6L, 6L, 6L, 6L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 
                                                                                                                                                5L, 5L, 5L, 5L, 5L, 5L, 5L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 
                                                                                                                                                4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 
                                                                                                                                                4L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
                                                                                                                                                3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
                                                                                                                                                3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                                                                                                                2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                                                                                                                2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                                                                                                                2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                                                                                                                2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                                                                                                                2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                                                                                                                2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                                                                                                                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), nr = c(-102, 99, 82, -60, 45, 
                                                                                                                                                                                        39, 36, 23, -22, -21, 19, -18, -18, 17, 16, 16, -15, 15, -15, 
                                                                                                                                                                                        -14, -14, 13, -13, 13, -12, 12, -12, 11, 11, -10, -10, 10, -9, 
                                                                                                                                                                                        9, 9, -9, 9, -9, -8, 8, -8, -8, -8, -8, 8, 7, -7, 7, 7, -7, -7, 
                                                                                                                                                                                        -7, 7, 7, -7, -7, 6, -6, -6, 6, -6, -6, -6, -6, -6, -6, -6, 5, 
                                                                                                                                                                                        -5, -5, -5, 5, 5, 5, -5, 5, 5, -5, 5, -5, -5, -5, 4, -4, 4, 4, 
                                                                                                                                                                                        4, 4, -4, -4, 4, -4, 4, 4, 4, -4, -4, 4, -4, 4, 4, 4, -4, 4, 
                                                                                                                                                                                        -4, -4, -4, 4, 3, 3, 3, 3, -3, -3, 3, 3, -3, 3, 3, -3, -3, -3, 
                                                                                                                                                                                        3, -3, -3, -3, -3, 3, 3, -3, -3, -3, -3, 3, 3, 3, 3, -3, 3, -3, 
                                                                                                                                                                                        3, 3, 3, 3, 3, -3, -3, 2, -2, -2, 2, 2, 2, -2, 2, 2, -2, -2, 
                                                                                                                                                                                        2, 2, -2, -2, -2, -2, 2, -2, 2, 2, -2, -2, 2, 2, 2, -2, -2, 2, 
                                                                                                                                                                                        -2, -2, 2, -2, 2, 2, 2, 2, 2, -2, -2, -2, 2, 2, 2, 2, -2, 2, 
                                                                                                                                                                                        2, 2, 2, 2, -2, -2, 2, -2, -2, -2, -2, -2, 2, 2, 2, 2, -2, -2, 
                                                                                                                                                                                        2, -2, -2, -2, -2, 2, -2, 2, -2, -2, -2, 2, 2, 2, 2, 2, 2, 2, 
                                                                                                                                                                                        -2, 2, -2, -2, -2, 2, 2, -2, -2, -2, -2, -2, -2, 2, 2, 2, -2, 
                                                                                                                                                                                        -2, 2, -2, -1, -1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, -1, -1, 
                                                                                                                                                                                        1, 1, 1, 1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 
                                                                                                                                                                                        -1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1, -1, 1, 1, -1, 
                                                                                                                                                                                        1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, -1, -1, -1, -1, -1, -1, 
                                                                                                                                                                                        -1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, 1, -1, 
                                                                                                                                                                                        -1, -1, -1, 1, -1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, -1, -1, 
                                                                                                                                                                                        -1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 
                                                                                                                                                                                        -1, -1, -1, 1, -1, -1, 1, -1, 1, 1, -1, 1, -1, -1, -1, -1, -1, 
                                                                                                                                                                                        1, -1, 1, -1, 1, 1, -1, 1, 1, 1, -1, -1, -1, 1, -1, -1, -1, 1, 
                                                                                                                                                                                        -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, -1, 1, -1, 
                                                                                                                                                                                        -1, -1, 1, -1, 1, 1, -1, -1, -1, 1, -1, 1, 1, -1, -1, -1, 1, 
                                                                                                                                                                                        -1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 
                                                                                                                                                                                        1, 1, -1, 1, -1, -1, 1, 1, 1, 1, -1, 1, 1, -1, 1, -1, 1, -1, 
                                                                                                                                                                                        -1, 1, -1, -1, -1, -1, -1, 1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, 
                                                                                                                                                                                        1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -1, -1, -1, -1, 
                                                                                                                                                                                        -1, 1, -1, 1, 1, 1, 1, -1, -1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 
                                                                                                                                                                                        -1, -1, 1)), .Names = c("word1", "word2", "score", "n", "nr"), class = c("tbl_df", 
                                                                                                                                                                                                                                                                 "tbl", "data.frame"), row.names = c(NA, -531L))
